### ISSUE TITLE
Amazon AWS MQTTs Connection Issue

### ISSUE THREAD

**Issue by Gruzzberry** [botletics/NB-IoT-Shield#328]
I seem to have gotten an issue with trying to connect to the Amazon AWS MQTT server. I have follows the commands exactly but get the same error as shown at the bottom. I believe the issue has come from the certificate, CA and key files. When uploading the originals they would not be accepted (AT+CSSLCFG=convert,1 and 2). After seeing a post about it being an issue with the newline characters (0A) in hex, I removed these and reuploaded the files as one line which got accepted.

However the connection has not being accepted. To test I used MQTTX using the same configurations I was easily able to connect. I have tried different configurations in regards to the MQTT packet settings (QoS, Will Message etc). I'm just wondering if me removing these characters would cause them to be invalid as trying the edited files on MQTTX resulted in a CONNECTION REFUSED. The connection isn't immediately refused it seems to timeout, any help at all will be accepted as been a long time issue.

AT+CPIN?
+CPIN: READY

OK
AT+CSQ
+CSQ: 12,99

OK
AT+CGREG?
+CGREG: 0,1

OK
AT+COPS?
+COPS: 0,0,"vodafone UK",3

OK
AT+CGNAPN
+CGNAPN: 0,""

OK
AT+CNACT=1,"pp.vodafone.co.uk"
OK

+APP PDP: ACTIVE
AT+CGDCONT=1,"IP","pp.vodafone.co.uk"
OK

AT+CNACT?
+CNACT: 1,"10.120.184.34"

OK

at+csslcfg=convert,2,CA1edit.pem
OK

AT+CSSLCFG="convert",1,"certificateedit.crt","privateedit.key"
OK

AT+CSSLCFG="sslversion",0,3
OK

AT+SMSSL=1,CA1edit.pem,certificateedit.crt
OK

AT+SMCONF="URL","XXXXXXXXXXXX-ats.iot.eu-west-2.amazonaws.com",8883
OK

AT+SMCONF="CLIENTID","Tracker"
OK

AT+SMCONF="KEEPTIME",60
OK

AT+CCLK?
+CCLK: "24/03/08,17:14:29+00"

OK

AT+SMCONN
+CME ERROR: operation not allowed

**Comment by Gruzzberry** [comment]
Update, using a different tool (EFS Explorer), I was able to get the original CA, key and crt file on the device which is now being accepted however I am still unable to make a connection as I get **+CME ERROR: operation not allowed**

**Comment by Mark-Wills** [comment]
I think it's time that someone with the appropriate knowledge made a step
by step YouTube video on how to get certificates onto the modem and then
communicate with MQTT servers, web servers etc as we see this same issue
come up multiple times and it's nothing to do with the botletics board, or
the library.

Can anyone step forward for the sake of humanity? 😀

**Comment by Gruzzberry** [comment]
So after a month long conversation with SimCom and Qualcomm they found that I was getting a fatal error. They made a beta version firmware which will allow me to connect but has seemingly broken GPS now.
