### ISSUE TITLE
SIM5320 Support is it suspended?

### ISSUE THREAD

**Issue by Snowfly-** [botletics/NB-IoT-Shield#43]
Hi...
Has there been significant changes on library regarding support on SIM5320 module.
Cause at this moment there comes compiling error 'class Adafruit_FONA_3G' has no member named 'setNetworkSettings'
Using LTE_DEMO example with correct changes to enable the SIM5320

**Comment by Snowfly-** [comment]
> Yes, the function name to set the APN was changed for the entire library. Please see the updated LTE_Demo which should compile fine for the new library.

Hi tested with latest LTE_Demo and it still uses fona.setNetworkSettings
Have you forgot to tupdate the LTE_demo for the library change?

**Comment by botletics** [comment]
I'm not sure what you're asking. If you use the latest LTE_Demo sketch along with the latest library, it will work. The example uses the fona.setNetworkSettings() function and so does the latest library version.

**Comment by Snowfly-** [comment]
> I'm not sure what you're asking. If you use the latest LTE_Demo sketch along with the latest library, it will work. The example uses the fona.setNetworkSettings() function and so does the latest library version.

Well redownloaded and installed the latest library and the LTE_DEMO. Tested compiling it with Arduino IDE 1.8.4 without any changes comes compiling error 'Adafruit_FONA_LTE' does not name a type.
Then changed the default #define SIMCOM 7000 to #define SIMCOM_3G and error becomes 'class Adafruit_FONA_3G' has no member named 'setNetworkSettings'

Could this be Arduino version problem or something else? because I can't figure anything else out why the library wouldn't work.

Thank you for your patience in this matter.

**Comment by botletics** [comment]
First of all, are you using the library in this GitHub page? You need to delete any other Adafruit FONA library you might have in your libraries folder or it won't work.

**Comment by Snowfly-** [comment]
Yes... and no other Adafruit Fona libraries installed.... tested removing folder and it disapeared from Arduino Ide

**Comment by botletics** [comment]
Sorry, I had a slight typo above. You need to get the library only from this GitHub repo, *not* from Adafruit. The fact that you're getting an "Adafruit_FONA_LTE does not name a type" error is a strong indicator that you're not using the right library.

**Comment by Snowfly-** [comment]
I took the repo SIM7000-LTE-Shield... renamed the code directory to Adafruit_FONA. Moved it to the arduino library folder where arduino finds it without problems.
Loaded the example LTE_Demo.
Tried compiling

**Comment by botletics** [comment]
Compiles great for me and I just took the files from Github directly. Works for both the LTE and 3G definitions. You must have some ghost version of the Adafruit library floating around in your libraries folder.

**Comment by Snowfly-** [comment]
Which Arduino Ide are you using?

**Comment by botletics** [comment]
1.8.7 but that doesn't matter, 1.8.4 is recent enough.

**Comment by botletics** [comment]
I would recommend doing a search in your libraries folder (Document/Arduino/libraries) for "FONA" and see which folders pop up. Remove all of them, then get the library from this Github page and put it in.

**Comment by Snowfly-** [comment]
Hmm... Intresting updated Arduino Ide to latest... and now I get bunch of warnings...

`
In file included from D:\Documents\Arduino\libraries\Adafruit_FONA\examples\LTE_Demo\LTE_Demo.ino:30:0:

D:\Documents\Arduino\libraries\Adafruit_FONA/Adafruit_FONA.h:157:76: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   boolean postData(const char *request_type, const char *URL, char *body = "", const char *token = "");

                                                                            ^

D:\Documents\Arduino\libraries\Adafruit_FONA/Adafruit_FONA.h:158:101: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   boolean postData(const char *server, uint16_t port, const char *connType, char *URL, char *body = "");

                                                                                                     ^

D:\Documents\Arduino\libraries\Adafruit_FONA\examples\LTE_Demo\LTE_Demo.ino: In function 'void loop()':

D:\Documents\Arduino\libraries\Adafruit_FONA\examples\LTE_Demo\LTE_Demo.ino:1003:38: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

         if (!fona.postData("GET", URL))

                                      ^

In file included from D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:19:0:

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.h:157:76: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   boolean postData(const char *request_type, const char *URL, char *body = "", const char *token = "");

                                                                            ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.h:158:101: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   boolean postData(const char *server, uint16_t port, const char *connType, char *URL, char *body = "");

                                                                                                     ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp: In member function 'boolean Adafruit_FONA::postData(const char*, const char*, char*, const char*)':

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:1660:51: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   if (! sendCheckReply(dataBuff, "DOWNLOAD", 10000))

                                                   ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp: In member function 'boolean Adafruit_FONA::postData(const char*, uint16_t, const char*, char*, char*)':

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:1769:42: warning: ISO C++ forbids converting a string constant to 'char*' [-Wwrite-strings]

   if (! sendCheckReply(auxStr, ">", 10000))

                                          ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp: In member function 'char* Adafruit_FONA::FTP_GET(const char*, const char*, uint16_t)':

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:2006:12: warning: converting 'false' to pointer type 'char*' [-Wconversion-null]

     return false;

            ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:2011:12: warning: converting 'false' to pointer type 'char*' [-Wconversion-null]

     return false;

            ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:2014:12: warning: converting 'false' to pointer type 'char*' [-Wconversion-null]

     return false;

            ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:2016:48: warning: converting 'false' to pointer type 'char*' [-Wconversion-null]

   if (! expectReply(F("+FTPGET: 1,1"))) return false;

                                                ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:2021:60: warning: converting 'false' to pointer type 'char*' [-Wconversion-null]

     if (strstr(replybuffer, "+FTPGET: 2,") == NULL) return false;

                                                            ^

D:\Documents\Arduino\libraries\Adafruit_FONA\Adafruit_FONA.cpp:2026:63: warning: converting 'false' to pointer type 'char*' [-Wconversion-null]

     if (strstr(replybuffer, "+FTPEXTGET: 2,") == NULL) return false;

                                                               ^`

**Comment by botletics** [comment]
Yea but at least it compiles and will work.

**Comment by Snowfly-** [comment]
Yeah... must be wierd bug on that older version... Thank you for the assistant...

**Comment by botletics** [comment]
Just fixed compile warnings, please use new library .cpp and .h files.

**Comment by Snowfly-** [comment]
Thank you
